language: android
android:
  components:
    - build-tools-26.0.1
    - android-26
    - extra
before_script:
  - export TERM=dumb
  # Approx. 3 seconds
  - curl -L https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip -O
  # Usually around 1 minute
  - unzip android-ndk-r14b-linux-x86_64.zip > /dev/null
  - rm android-ndk-r14b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r14b
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - env
script:
  - ./gradlew build